server:
  port: 8888
  host: localhost
db:
  port: 3307
  host: localhost
  user: root
  password: password
  database: godev
  charset: utf8mb4
  parse_time: True
  loc: Local
security:
  jwt:
    token_secret: abc
